# 代理设置
proxy:
  # 协议
  protocol: http
  # 主机
  host: 127.0.0.1
  # 端口号
  port: 1081

# 认证信息
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImJjNDI1ODNhLTI5NGQtNDI1Ny04ZGZmLTMzMDc0MDljNjc5ZCIsInR5cGUiOiJyZWZyZXNoX3Rva2VuIiwiaXNzIjoiaXdhcmEiLCJpYXQiOjE2ODAyNjcwODEsImV4cCI6MTY4Mjg1OTA4MX0.8cn1GGJkOAmaI6DMr7RnGgWR0LeJ_G_XcIuGVcW4Owk

# 请求超时时间（单位毫秒 1秒=1000毫秒） 默认值 5000
timeout: 5000
maxTaskNum: 2
# 下载路径
savePath: D:\Download\test
